palabra = input("Introduce una palabra: ")
num_int = int(input("Introduce un numero entero: "))
num_float = float(input("Introduce un numero flotante: "))
num_complex = complex(input("Introduce un nuero complejo: "))
print("String: ", palabra)
print("Entero: ", num_int)
print("Flotante: ", num_float)
print("Numero Complejo: ", num_complex)
